import unittest

from app.capabilities import FfmpegCapabilities

SAMPLE_FFMPEG_OUTPUT = """
Encoder h264_nvenc [NVIDIA NVENC H.264 encoder]:
    General capabilities: delay threads hardware
    Threading capabilities: none
    Supported pixel formats: yuv420p nv12 p010le yuv444p p016le yuv444p16le bgr0 rgb0 cuda
h264_nvenc AVOptions:
  -preset            <int>        E..V....... Set the encoding preset (from 0 to 18) (default p4)
     default         0            E..V.......
     slow            1            E..V....... hq 2 passes
     medium          2            E..V....... hq 1 pass
     fast            3            E..V....... hp 1 pass
     hp              4            E..V.......
     hq              5            E..V.......
     bd              6            E..V.......
     ll              7            E..V....... low latency
     llhq            8            E..V....... low latency hq
     llhp            9            E..V....... low latency hp
     lossless        10           E..V.......
     losslesshp      11           E..V.......
     p1              12           E..V....... fastest (lowest quality)
     p2              13           E..V....... faster (lower quality)
     p3              14           E..V....... fast (low quality)
     p4              15           E..V....... medium (default)
     p5              16           E..V....... slow (good quality)
     p6              17           E..V....... slower (better quality)
     p7              18           E..V....... slowest (best quality)
  -profile           <int>        E..V....... Set the encoding profile
     baseline        0            E..V.......
     main            1            E..V.......
     high            2            E..V.......
     high444p        3            E..V.......
  -level             <int>        E..V....... Set the encoding level restriction
     auto            0            E..V.......
     1               10           E..V.......
     1.0             10           E..V.......
     1b              9            E..V.......
     1.0b            9            E..V.......
     1.1             11           E..V.......
     1.2             12           E..V.......
     1.3             13           E..V.......
     2               20           E..V.......
     2.0             20           E..V.......
     2.1             21           E..V.......
     2.2             22           E..V.......
     3               30           E..V.......
     3.0             30           E..V.......
     3.1             31           E..V.......
     3.2             32           E..V.......
     4               40           E..V.......
     4.0             40           E..V.......
     4.1             41           E..V.......
     4.2             42           E..V.......
     5               50           E..V.......
     5.0             50           E..V.......
     5.1             51           E..V.......
     5.2             52           E..V.......
     6               60           E..V.......
     6.0             60           E..V.......
     6.1             61           E..V.......
     6.2             62           E..V.......
  -rc                <int>        E..V....... Override the preset rate-control
     constqp         0            E..V....... Constant QP mode
     vbr             1            E..V....... Variable bitrate mode
     cbr             2            E..V....... Constant bitrate mode
     vbr_minqp       3            E..V....... Variable bitrate mode with MinQP
     ll_2pass_quality 4           E..V....... Multi-pass optimized for image quality
     ll_2pass_size   5            E..V....... Multi-pass optimized for constant frame size
     vbr_2pass       6            E..V....... Multi-pass variable bitrate mode
     vbr_hq          7            E..V....... Variable bitrate mode with high quality
     cbr_hq          8            E..V....... Constant bitrate mode with high quality
     vbr_lossless    9            E..V....... Variable bitrate mode with lossless
     cbr_lossless    10           E..V....... Constant bitrate mode with lossless
  -rc-lookahead      <int>        E..V....... Number of frames to look ahead
"""


class TestCapabilitiesParsing(unittest.TestCase):
    def test_rc_parsing(self):
        # We need to test the private method _choices_from_help using our sample output
        # FfmpegCapabilities doesn't expose it publicly, but we can access it for testing

        # Instantiate with skip_detection=True so it doesn't try to run ffmpeg
        caps = FfmpegCapabilities(skip_detection=True)

        # Manually call the method
        choices = caps._choices_from_help(SAMPLE_FFMPEG_OUTPUT, "rc")

        print(f"Parsed choices: {choices}")

        # Assertions
        self.assertIn("vbr", choices, "Should detect 'vbr'")
        self.assertIn("constqp", choices, "Should detect 'constqp'")
        self.assertIn("vbr_hq", choices, "Should detect 'vbr_hq'")
        self.assertIn("cbr", choices, "Should detect 'cbr'")


if __name__ == "__main__":
    unittest.main()
